log: 'core'
access_log: 1
show_errors: 1
sites:
        37signals:
                name: '37Signals'
                client_id: ''
                client_secret: ''
                site: 'https://launchpad.37signals.com/'
                authorize_path: '/authorization/new'
                access_token_path: '/authorization/token'
                protected_resource_path: '/authorization.xml'
        facebook:
                name: 'Facebook'
                client_id: ''
                client_secret: ''
                site: 'https://graph.facebook.com'
                protected_resource_path: '/me'
        mixi:
                name: 'mixi'
                client_id: ''
                client_secret: ''
                site: 'https://mixi.jp'
                authorize_url: 'https://mixi.jp/connect_authorize.pl'
                access_token_url: 'https://secure.mixi-platform.com/2/token'
        google:
                name: 'Google Contacts'
                client_id: ''
                client_secret: ''
                site: 'https://accounts.google.com'
                authorize_path: '/o/oauth2/auth'
                access_token_path: '/o/oauth2/token'
                scope: 'https://www.google.com/m8/feeds/'
                protected_resource_url: 'https://www.google.com/m8/feeds/contacts/default/full'
                access_token_param: 'oauth_token'
